name: "Get group number"
description: "Get group number based on repository name"
runs:
  using: "composite"
  steps:
    - name: "Get group number"
      env:
        GROUP_NAME: ${{ github.event.repository.name }}
        run: GROUP=$(echo $GROUP_NAME | cut -d '-' -f 1) && echo $GROUP_NAME && echo $GROUP
