name: "Deploy lambda"
description: "Deploy lambda to AWS environment"

runs:
  using: "composite"
  steps:
    - name: "Get gruop id"
      uses: ./.github/actions/get-group-number
      id: group-number
    - name: "Deploy zipped lambda"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-west-1"
        GROUP_ID: ${{ steps.group-number.outputs.group-number }}
      run: echo $GROUP_ID
      shell: bash
