name: "Deploy lambda"
description: "Deploy lambda to AWS environment"

inputs:
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  ZIP_FILE_PATH:
    description: "Path to the zipped file"
    required: true
  STEP_NAME:
    required: true
  ARTIFACTS_BUCKET:
    required: true
  LAMBDA_NAME:
    required: false
    default: "default"
    description: 'Name of the lambda function. For steps with several lambdas, its important to note the name. Otherwise, leave it blank as "default" is used'

runs:
  using: "composite"
  steps:
    - name: "Get gruop id"
      uses: ./.github/actions/get-group-name
      id: group-name
    - name: "Deploy zipped lambda"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-west-1"
      run: aws s3 cp ${{ inputs.ZIP_FILE_PATH }} s3://${{ inputs.ARTIFACTS_BUCKET }}/deployments/${{ steps.group-name.outputs.group-name }}/${{ inputs.STEP_NAME }}/${{ LAMBDA_NAME }}.zip
      shell: bash
