name: "Push step 1 infra to AWS"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'cs2-case-template-python'

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/get-group-number
        id: group-name
      - run: cd src/step1 && zip -r index.zip .
      - uses: ./github/actions/deploy-lambda
