name: "Push step 2 infra to AWS"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'cs2-case-template-python'

    steps:
      - uses: actions/checkout@v3
      - run: cp src/config.py src/step2/config.py && cd src/step2 && zip -r index.zip .
      - uses: ./.github/actions/deploy-lambda
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ZIP_FILE_PATH: "src/step2/index.zip"
          ARTIFACTS_BUCKET: "cs2-case-st24-lambda-deployments"
          STEP_NAME: "step2"
