name: "Push step 1 infra to AWS"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'cs2-case-template-python'

    steps:
      - uses: actions/checkout@v3
      - run: cd src/step1 && zip -r index.zip .
      - uses: ./.github/actions/deploy-lambda
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
