name: "Deploy battleship"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'cs2-case-template-python'

    steps:
      - uses: actions/checkout@v4
      - run: cp src/config.py src/battleship/config.py && cp src/battleship/lambda/main.py src/battleship/main.py && cd src/battleship && zip -r index.zip .
      - uses: ./.github/actions/deploy-lambda
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ZIP_FILE_PATH: "src/battleship/index.zip"
          ARTIFACTS_BUCKET: "cs2-case-st24-lambda-deployments"
          STEP_NAME: "step3"
