name: "Initialize repository"

on:
  workflow_dispatch:

  # schedule:
  # - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  initialize:
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'cs2-case-template-python'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/get-group-name
        id: group-name
      - name: Rename artifacts in repository
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
          GROUP_NAME: ${{ github.event.repository.name }}
        run: |
          sed -i "s/<name-prefix>/$NAME_PREFIX/g" README.md
          sed -i "s,<group-number>,${{ steps.group-name.outputs.group-name }},g" src/config.py
          rm .github/workflows/init.yml
      - name: Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit --amend --no-edit
          git push --force
